version: '3.8'
services:
  db:
    image: postgres:13
    container_name: gym_exercices_fullstack-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gym_database
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build:
      context: .
    container_name: gym_exercices_fullstack-backend
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/gym_database"
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "8000:8000"  # Expose le port 8000
    volumes:
      - ./dataset:/app/dataset  # Montez le dossier dataset dans le conteneur

networks:
  app-network:
  